<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auction.DAL\Auction.DAL.csproj" />
    <ProjectReference Include="..\Auction.Entities\Auction.Entities.csproj" />
  </ItemGroup>

</Project>
